version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./routes/common/models:/app/routes/common/models
      - ./uploaded_images:/app/uploaded_images
    environment:
      - PYTHONUNBUFFERED=1
    restart: always